#Introduction to Numpy
    
    

In [1]:
!pip install numpy

    Importing Numpy

In [2]:
import numpy as np #np is alias name

In [3]:
even = [6,8,6,4,12,14]
len(even)

6

In [4]:
even_array = np.array(even)
even_array


array([ 6,  8,  6,  4, 12, 14])

In [6]:
even_array[0]

6

In [7]:
even_array[1]

8

In [8]:
even_array[4]

12

In [9]:
even_array[-1] #negative indexing

14

In [10]:
even_array[-4]

6

In [11]:
even_array[-3]

4

In [12]:
even_array[1:3] #slicing ma last ko index ko value aaudaina

array([8, 6])

In [13]:
even_array.ndim

1

# Difference between list and array

- Numpy array are faster than python list 
- Numpy array are memory efficient than python list
- Numpy array supports homogeneous data type while pythonlist supports multiple data type
- 


In [15]:
x = np.zeros(5,dtype = np.int8)
x

array([0, 0, 0, 0, 0], dtype=int8)

In [18]:
np.ones(3,dtype = np.float16)

array([1., 1., 1.], dtype=float16)

In [34]:
np.random.randint(0,10) #non deterministic random number generation

3

In [44]:
np.random.seed(0)
np.random.randint(0,10)

5

In [49]:
np.random.seed(2024)
x = np.random.randint(1,10, size = 50000)

In [50]:
x_list = x.tolist() # converts array into list

In [53]:
a = [8,9,7]
sq = []
for item in a:
    sq.append(item ** 2)

In [54]:
sq

[64, 81, 49]

In [55]:
[item ** 2 for item in a] #list comprehension

[64, 81, 49]

In [57]:
%%time 
sq = [item ** 2for item in x_list]

CPU times: total: 15.6 ms
Wall time: 10.9 ms


<unknown>:1: SyntaxWarning: invalid decimal literal


In [58]:
%%time
sq = x ** 2


CPU times: total: 0 ns
Wall time: 998 µs


 .linspace()

In [59]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [61]:
np.arange(11,24,1)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [62]:
x = np.array([4,9])
y = np.array([2,3])

In [64]:
x + y #element wise addition or vector addition

array([ 6, 12])

In [65]:
x / y

array([2., 3.])

In [68]:
x*y

array([ 8, 27])

 Statistics

In [71]:
x = np.random.randint(1,20,size = 40)

In [72]:
x

array([13, 14,  8, 11, 16,  6, 16,  8,  5,  1, 17,  5, 18, 11, 11, 19, 15,
        8, 15, 11,  4, 17, 10,  4,  3, 14,  7,  1,  5, 16, 14, 16,  7, 14,
       14, 11,  2,  2, 12, 11])

In [73]:
np.mean(x)

10.3

In [74]:
np.median(x)

11.0

In [75]:
np.std(x)

5.158488150611572

In [76]:
from scipy.stats import mode
mode(x)

ModeResult(mode=11, count=6)

In [77]:
np.var(x) #variance

26.610000000000003

# 2D array

In [79]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
matrix.ndim

2

In [82]:
matrix[1,2]

6

In [83]:
matrix [2,1]

8

In [85]:
matrix[1:,1:]

array([[5, 6],
       [8, 9]])